# Generated by Django 5.2.17 on 2026-08-29 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ім’я')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('context', models.CharField(blank=True, max_length=255, verbose_name='Джерело CTA')),
                ('package', models.CharField(blank=True, max_length=64, verbose_name='Пакет')),
                ('object_type', models.CharField(blank=True, max_length=64, verbose_name='Тип об’єкта')),
                ('area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Площа, м²')),
                ('calc_summary', models.TextField(blank=True, verbose_name='Параметри розрахунку')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('called', 'Передзвонили'), ('rejected', 'Відмова'), ('success', 'Успіх')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Лід',
                'verbose_name_plural': 'Ліди',
                'ordering': ('-created_at',),
            },
        ),
    ]
