# Generated by Django 5.2.17 on 2026-09-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('standard', 'Картка'), ('cta', 'CTA-картка')], default='standard', max_length=16, verbose_name='Тип')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='advantages/', verbose_name='Фото')),
                ('image_static', models.CharField(blank=True, max_length=255, verbose_name='Static fallback')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt')),
                ('cta_label', models.CharField(blank=True, max_length=120, verbose_name='CTA текст')),
                ('cta_href', models.CharField(blank=True, max_length=255, verbose_name='CTA посилання')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Локація')),
                ('text', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='cases/', verbose_name='Фото')),
                ('image_static', models.CharField(blank=True, max_length=255, verbose_name='Static fallback')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt')),
                ('tags', models.TextField(blank=True, help_text='Кожен рядок — окремий тег', verbose_name='Теги (по рядку)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейси',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='DesignFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Пункт')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Пункт дизайну',
                'verbose_name_plural': 'Пункти дизайну',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Фото')),
                ('image_url', models.URLField(blank=True, verbose_name='URL фото (fallback)')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Hero-слайд',
                'verbose_name_plural': 'Hero-слайди',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Ціна $/м²')),
                ('price_unit', models.CharField(default='$/м²', max_length=32, verbose_name='Одиниця ціни')),
                ('features', models.TextField(blank=True, help_text='Кожен рядок — окремий пункт списку', verbose_name='Склад (по рядку)')),
                ('badge', models.CharField(blank=True, max_length=64, verbose_name='Бейдж')),
                ('cta_label', models.CharField(default='Замовити', max_length=64, verbose_name='Текст кнопки')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакети',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Відгук')),
                ('name', models.CharField(max_length=80, verbose_name='Ім’я')),
                ('meta', models.CharField(blank=True, max_length=120, verbose_name='Підпис')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kontur+', max_length=128, verbose_name='Назва сайту')),
                ('brand_desc', models.CharField(blank=True, default='ремонтна організація', max_length=128, verbose_name='Опис бренду')),
                ('phone_display', models.CharField(blank=True, max_length=32, verbose_name='Телефон (відображення)')),
                ('phone_tel', models.CharField(blank=True, max_length=32, verbose_name='Телефон (tel:)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='Місто')),
                ('work_hours', models.CharField(blank=True, max_length=128, verbose_name='Години роботи')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='StyleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Назва')),
                ('text', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='styles/', verbose_name='Фото')),
                ('image_url', models.URLField(blank=True, verbose_name='URL фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стилі',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('privacy', 'Privacy')], max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'Посилання')], default='text', max_length=16)),
                ('text_html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('link_url', models.CharField(blank=True, max_length=512)),
                ('link_label', models.CharField(blank=True, max_length=128)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ('page', 'sort_order', 'key'),
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
        migrations.CreateModel(
            name='HomeAdvantagesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Переваги',
                'verbose_name_plural': 'Переваги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCalculatorSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Калькулятор',
                'verbose_name_plural': 'Калькулятор',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeDesignSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Дизайн',
                'verbose_name_plural': 'Дизайн',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeFaqSettings',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Банер (Hero)',
                'verbose_name_plural': 'Банер (Hero)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomePackagesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Пакети',
                'verbose_name_plural': 'Пакети',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeProofSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Відгуки та кейси',
                'verbose_name_plural': 'Відгуки та кейси',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeStylesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Стилі',
                'verbose_name_plural': 'Стилі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='PrivacyPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Privacy',
                'verbose_name_plural': 'Privacy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteHeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка сайту',
                'verbose_name_plural': 'Шапка сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteModalSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Модальне вікно',
                'verbose_name_plural': 'Модальне вікно',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
    ]
