# Generated by Django 5.2.17 on 2026-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_advantageitem_caseitem_designfeature_faqitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ('sort_order', 'pk'), 'verbose_name': 'Питання та відповідь', 'verbose_name_plural': 'Питання та відповіді'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ('sort_order', 'pk'), 'verbose_name': 'Фото банера', 'verbose_name_plural': 'Фото банера'},
        ),
        migrations.AlterModelOptions(
            name='homefaqsettings',
            options={'verbose_name': 'Питання та відповіді', 'verbose_name_plural': 'Питання та відповіді'},
        ),
        migrations.AlterModelOptions(
            name='homeherosettings',
            options={'verbose_name': 'Головний банер', 'verbose_name_plural': 'Головний банер'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='privacypagesettings',
            options={'verbose_name': 'Політика конфіденційності', 'verbose_name_plural': 'Політика конфіденційності'},
        ),
        migrations.AlterModelOptions(
            name='sitefootersettings',
            options={'verbose_name': 'Підвал сайту', 'verbose_name_plural': 'Підвал сайту'},
        ),
        migrations.AlterModelOptions(
            name='sitemodalsettings',
            options={'verbose_name': 'Форма дзвінка', 'verbose_name_plural': 'Форма дзвінка'},
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='cta_href',
            field=models.CharField(blank=True, max_length=255, verbose_name='Куди веде посилання'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='cta_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст посилання'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткий опис фото'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='image_static',
            field=models.CharField(blank=True, help_text='Службове поле. Зазвичай достатньо завантажити фото вище.', max_length=255, verbose_name='Запасний шлях до фото'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='kind',
            field=models.CharField(choices=[('standard', 'Звичайна картка'), ('cta', 'Картка з кнопкою')], default='standard', max_length=16, verbose_name='Тип картки'),
        ),
        migrations.AlterField(
            model_name='caseitem',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткий опис фото'),
        ),
        migrations.AlterField(
            model_name='caseitem',
            name='image_static',
            field=models.CharField(blank=True, help_text='Службове поле. Зазвичай достатньо завантажити фото вище.', max_length=255, verbose_name='Запасний шлях до фото'),
        ),
        migrations.AlterField(
            model_name='caseitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='caseitem',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='Місце / район'),
        ),
        migrations.AlterField(
            model_name='caseitem',
            name='tags',
            field=models.TextField(blank=True, help_text='Кожен рядок — окремий тег під описом кейсу', verbose_name='Теги робіт'),
        ),
        migrations.AlterField(
            model_name='designfeature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Для доступності: що зображено на фото', max_length=200, verbose_name='Короткий опис фото'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_url',
            field=models.URLField(blank=True, help_text='Якщо файл не завантажено — можна вставити посилання на зображення', verbose_name='Посилання на фото'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='calc_summary',
            field=models.TextField(blank=True, verbose_name='Деталі розрахунку'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='context',
            field=models.CharField(blank=True, max_length=255, verbose_name='Звідки заявка'),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='badge',
            field=models.CharField(blank=True, help_text='Наприклад: «Рекомендуємо»', max_length=64, verbose_name='Мітка на картці'),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='features',
            field=models.TextField(blank=True, help_text='Кожен рядок — окремий пункт у списку на сайті', verbose_name='Що входить у пакет'),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендований пакет'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='page',
            field=models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('privacy', 'Конфіденційність')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Короткий текст у результатах пошуку (до ~160 символів)', max_length=255, verbose_name='Опис для Google'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_display',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон на сайті'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_tel',
            field=models.CharField(blank=True, help_text='Лише цифри з +380… — для кнопки «подзвонити»', max_length=32, verbose_name='Телефон для дзвінка'),
        ),
        migrations.AlterField(
            model_name='styleitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Якщо файл не завантажено — можна вставити посилання', verbose_name='Посилання на фото'),
        ),
        migrations.AlterField(
            model_name='styleitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
    ]
