# Generated by Django 5.2.17 on 2026-09-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_admin_ux_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantageitem',
            name='icon',
            field=models.CharField(blank=True, choices=[('price', 'Документ / ціна'), ('package', 'Пакет / коробка'), ('calendar', 'Календар / строк'), ('shield', 'Щит / гарантія'), ('pin', 'Мітка / локація'), ('none', 'Без іконки')], default='price', max_length=32, verbose_name='Іконка'),
        ),
    ]
