# Generated by Django 5.2.17 on 2026-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_advantage_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ('sort_order', 'pk'), 'verbose_name': 'Кадр банера', 'verbose_name_plural': 'Кадри банера'},
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='Опційно: MP4/WebM замість фото. Фото тоді стає постером.', upload_to='hero/video/', verbose_name='Відео (файл)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video_url',
            field=models.URLField(blank=True, help_text='Альтернатива файлу — пряме посилання на MP4/WebM', verbose_name='Посилання на відео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_area_max',
            field=models.PositiveSmallIntegerField(default=150, verbose_name='Макс. площа калькулятора, м²'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_area_min',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Мін. площа калькулятора, м²'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_billable_min',
            field=models.PositiveSmallIntegerField(default=40, help_text='Якщо фактична менша — для суми береться це значення', verbose_name='Мін. розрахункова площа, м²'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_coef_31_34',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=4, verbose_name='Коеф. 31–34 м²'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_coef_35_39',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=4, verbose_name='Коеф. 35–39 м²'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_coef_to_30',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=4, verbose_name='Коеф. до 30 м²'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_pay_1',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Частка від суми (0.30 = 30%)', max_digits=4, verbose_name='Оплата 1 · договір'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_pay_2',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=4, verbose_name='Оплата 2 · матеріали'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_pay_3',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=4, verbose_name='Оплата 3 · 75% робіт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calc_pay_4',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=4, verbose_name='Оплата 4 · акт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Наприклад 4.9. Пізніше можна підтягувати з Places API.', max_digits=2, null=True, verbose_name='Рейтинг Google'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_reviews_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість відгуків Google'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_reviews_url',
            field=models.URLField(blank=True, help_text='Кнопка «дивитись у Google» / Places API пізніше', verbose_name='Посилання на Google-відгуки'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Для доступності: що зображено на кадрі', max_length=200, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, upload_to='hero/', verbose_name='Фото / постер'),
        ),
    ]
