# Generated by Django 5.2.17 on 2026-09-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_calc_hero_rating_deploy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandColorSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Колір бренду',
                'verbose_name_plural': 'Колір бренду',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitesettings',),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_button',
            field=models.CharField(default='#dff250', help_text='Заливка акцентних кнопок (формат #RRGGBB)', max_length=7, verbose_name='Колір кнопки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_button_hover',
            field=models.CharField(default='#eaff6b', help_text='Колір кнопки при наведенні', max_length=7, verbose_name='Кнопка · hover'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_button_text',
            field=models.CharField(default='#16181a', help_text='Колір тексту / іконок на акцентних кнопках', max_length=7, verbose_name='Текст на кнопці'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_fill',
            field=models.CharField(default='#dff250', help_text='Салатова заливка карток і акцентних блоків', max_length=7, verbose_name='Заливка блоків'),
        ),
    ]
