# Generated by Django 5.2.17 on 2026-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_brand_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent_icon',
            field=models.CharField(default='#a8bc22', help_text='Крапки, лапки, іконки футера', max_length=7, verbose_name='Акцент · іконки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent_text',
            field=models.CharField(default='#7e8f1c', help_text='Ціни в активному пакеті, посилання, темний акцент тексту', max_length=7, verbose_name='Акцент · текст'),
        ),
    ]
