# Generated by Django 5.2.17 on 2026-09-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_brand_accent_icon_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent_icon',
            field=models.CharField(default='#b19d91', help_text='Крапки, лапки, іконки футера', max_length=7, verbose_name='Акцент · іконки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent_text',
            field=models.CharField(default='#806252', help_text='Ціни в активному пакеті, посилання, темний акцент тексту', max_length=7, verbose_name='Акцент · текст'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_button',
            field=models.CharField(default='#b1a091', help_text='Заливка акцентних кнопок (формат #RRGGBB)', max_length=7, verbose_name='Колір кнопки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_button_hover',
            field=models.CharField(default='#b0a091', help_text='Колір кнопки при наведенні', max_length=7, verbose_name='Кнопка · hover'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_fill',
            field=models.CharField(default='#b0a091', help_text='Салатова заливка карток і акцентних блоків', max_length=7, verbose_name='Заливка блоків'),
        ),
    ]
