# Generated by Django 5.2.17 on 2026-09-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_brand_taupe_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='external_key',
            field=models.CharField(blank=True, db_index=True, help_text='Ідентифікатор відгуку з Google Places (для sync).', max_length=255, verbose_name='Зовнішній ключ'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='source',
            field=models.CharField(choices=[('manual', 'Ручний (резерв)'), ('google', 'Google Places')], db_index=True, default='manual', max_length=16, verbose_name='Джерело'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Ідентифікатор місця (ChIJ…) або посилання Google Maps з place_id. Ключ API — у .env (GOOGLE_PLACES_API_KEY).', max_length=255, verbose_name='Google Place ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_reviews_auto_sync',
            field=models.BooleanField(default=True, help_text='Оновлювати рейтинг і відгуки командою sync_google_reviews / кнопкою в CMS.', verbose_name='Автосинхронізація відгуків'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_reviews_sync_error',
            field=models.CharField(blank=True, editable=False, max_length=500, verbose_name='Помилка останньої синхронізації'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_reviews_synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Остання синхронізація Google'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Оновлюється з Places API; можна задати вручну як запасний варіант.', max_digits=2, null=True, verbose_name='Рейтинг Google'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_reviews_count',
            field=models.PositiveIntegerField(blank=True, help_text='Оновлюється з Places API; запасне значення — вручну.', null=True, verbose_name='Кількість відгуків Google'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_reviews_url',
            field=models.URLField(blank=True, help_text='Кнопка «дивитись у Google». Підставляється з API або вручну.', verbose_name='Посилання на Google-відгуки'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key', ''), _negated=True), fields=('source', 'external_key'), name='review_source_external_key_uniq'),
        ),
    ]
